### ISSUE TITLE
Automatically detecting file formats

### ISSUE THREAD

**Issue by asterized** [DemiCloud/universal-media-metadata#11]
Could automatically detect file format in absence of explicit filetype

**Comment by Gorian** [comment]
This is resolved with https://github.com/DemiCloud/universal-media-metadata/commit/d2a3683d2f5ef7c70f29ef2740d71b0e35d2d3e4

**Comment by Gorian** [comment]
This is resolved with https://github.com/DemiCloud/universal-media-metadata/commit/d2a3683d2f5ef7c70f29ef2740d71b0e35d2d3e4
